name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: ESLINT_NO_DEV_ERRORS=true  npm run build
        continue-on-error: true    
        
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::843498826545:role/GitHubAction-aau-livaatverse-unity-test
          aws-region: me-south-1  
          
      - name: Deploy to S3
        env:
          AWS_REGION: 'ap-southeast-2'  # e.g., us-east-1
          S3_BUCKET: 'vapor-ap-southeast-2-assets-1722266170'
        run: |
          aws s3 sync build/ s3://$S3_BUCKET/frontend-tech-test --delete
